# Generated by Django 4.0.4 on 2024-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_course_faculty_name_course_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='facultyKey',
            field=models.IntegerField(),
        ),
    ]
